- name: 1 - Creating Web Application - FriendlyBudget
  hosts: dbserver
  
  #handlers:
  #  - name: restart mysql
  #    service:
  #      name: mysql
  #      state: restarted
  #    become: yes
  
  tasks:
    - name: Update APT package manager repositories cache
      become: yes
      apt:
        update_cache: yes

    - name: Install MySQL
      become: yes
      apt:
        name: mysql-server
        state: present

    - name: Install Python for MySQL commands
      become: yes
      apt:
        name: python3-mysqldb
        state: present
    
    - name: git clone project
      git:
        repo: https://github.com/ArthurMPassos/FriendlyBudget.git
        dest: /home/vagrant/FriendlyBudget
        version: ansible-jenkins
        force: yes

    - name: 'Copiar arquivo mysqld.cnf'
      copy:
        src: /vagrant/configs/mysqld.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        owner: root
        group: root
        mode: 0644
      become: yes
      #notify: 
      #  - restart mysql

    - name: Configure MySQL
      become: yes
      shell: chmod 777 configure_mysql.bash
      args:
        chdir: FriendlyBudget/Scripts/

    - name: 'Criar usuario no MySQL'
      become: yes
      mysql_user:
        login_user: root
        name: admin
        password: admin
        priv: '*.*:ALL'
        host: '%'
        state: present

    - name: Configure MySQL part 2
      become: yes
      shell: ./configure_mysql.bash
      args:
        chdir: FriendlyBudget/Scripts/  

- hosts: backend
  tasks:
    - name: Update APT package manager repositories cache
      become: yes
      apt:
        update_cache: yes

    - name: Install Java
      become: yes
      apt:
        name: openjdk-8-jdk-headless
        state: present
    
    - name: git clone project
      git:
        repo: https://github.com/ArthurMPassos/FriendlyBudget.git
        dest: /home/vagrant/FriendlyBudget
        version: ansible-jenkins
    
    - name: Run Java Server Backend
      shell: java -jar friendlyBudget-0.0.1-SNAPSHOT.jar &
      args:
        chdir: /home/vagrant/FriendlyBudget/Backend/target

- hosts: frontend
  become: true
  gather_facts: yes

  tasks:
    - name: Install PHP
      apt:
        name: php-cli
        state: present
        update_cache: yes

    - name: Install git
      apt:
       name: git
       state: present
       update_cache: yes

    - name: Update APT package manager repositories cache
      become: yes
      apt:
        update_cache: yes
      
    - name: git clone project
      git:
        repo: https://github.com/ArthurMPassos/FriendlyBudget.git
        dest: /home/vagrant/FriendlyBudget
        version: ansible-jenkins
      
    - name: Start PHP
      shell: php -S 0.0.0.0:10000 &
      args:
        chdir: /home/vagrant/FriendlyBudget/Frontend


# - hosts: ansible
#   vars:
#     jenkins:
#     name: jenkins
#       jenkins_key_rpmU: https://pkg.jenkins.io/debian-stable/jenkins.io.key
#       jenkins_key_rpm: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

#   tasks:
#     - name: Update APT package manager repositories cache
#       become: true
#       apt:
#         update_cache: yes
#     - name: Install Java using Ansible
#       become: yes
#       apt:
#         name: "{{ packages }}"
#         state: present
#       vars:
#         packages:
#            - openjdk-11-jdk

#     - name: add jenkins key
#       apt_key:
#         state: present
#         url: "{{ jenkins_key_rpmU }}"

#     - name: "Set EPEL yum repository"
#       apt_repository:
#         filename: "{{ item.value.name }}"
#         repo: "{{ item.value.url }}"
#         description: "{{ item.value.description }}"
#       loop:
#         "{{ lookup('dict',reposU) }}"

#     - name: "Install Java and Jenkins"
#       apt:
#         name: "{{ item.value.name }}"
#         state: present
#       loop:
#         "{{ lookup('dict',softwaresU) }}"

#     - name: "Starting jenkins"
#       service:
#         name: "jenkins"
#         state: started
#         enabled: yes

#     - name: Install Maven using Ansible
#       become: yes
#       apt:
#         name: "{{ packages }}"
#         state: present
#       vars:
#         packages:
#            - maven
