Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/impish64"

  config.vm.define :dbserver do |db|
    db.vm.hostname = "db"
    db.vm.network "public_network", ip: "192.168.1.21"
  end

  config.vm.define :frontend do |front|
    front.vm.hostname = "front"
    front.vm.network "forwarded_port", guest: 10000, host: 8123, host_ip: "127.0.0.1"
    front.vm.network "public_network", ip: "192.168.1.22"
  end

  config.vm.define :backend do |back|
    back.vm.hostname = "back"
    back.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
    back.vm.network "public_network", ip: "192.168.1.23"
  end

  config.vm.define :ansible do |ansible|
    ansible.vm.hostname = "ansible"
    ansible.vm.network "public_network", ip: "192.168.1.20"
    ansible.vm.provision "shell",
                inline: "apt-get update && \
                         apt-get install -y software-properties-common && \
                         apt-add-repository --yes --update ppa:ansible/ansible && \
                         apt-get install -y ansible"
                    
    ansible.vm.provision "shell",
                  inline: "ansible-playbook -i /vagrant/configs/ansible/hosts \
                           /vagrant/configs/ansible/playbook.yml"
  end
  


  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    git clone https://github.com/ArthurMPassos/FriendlyBudget/
    cd FriendlyBudget
    sudo apt install mysql-server -y
    sudo chmod 777 Scripts/configure_mysql.bash
    sudo ./Scripts/configure_mysql.bash
    sudo apt install openjdk-8-jdk-headless -y
    java -jar Backend/target/friendlyBudget-0.0.1-SNAPSHOT.jar &
    cd Frontend
    sudo apt install php-cli -y 
    php -S 0.0.0.0:10000 &
  SHELL
end
